// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.DAL.Context;

#nullable disable

namespace Restaurant.DAL.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20231207192601_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.DAL.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Eveniet voluptatem rerum laboriosam hic consequatur occaecati.",
                            Name = "Pepperoni"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Enim esse accusamus rerum laudantium placeat est.",
                            Name = "Hawaiian Roll"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Architecto vitae consequuntur dolor deserunt perspiciatis consequuntur.",
                            Name = "Vegetarian Pizza"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Veniam qui saepe facere dolores occaecati molestiae.",
                            Name = "BBQ Chicken"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sint sint quas ipsum temporibus cumque voluptatem.",
                            Name = "Margherita"
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.DishIngredient", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "IngredientId")
                        .HasName("PK_DishIngredient");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            DishId = 2,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 10
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 5
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 5
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 10
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 10
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 8
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Eveniet voluptatem rerum laboriosam hic.",
                            Name = "Italian Sausage"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Occaecati facilis enim esse accusamus.",
                            Name = "Artichoke Hearts"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Laudantium placeat est qui architecto.",
                            Name = "Sun-Dried Tomatoes"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Consequuntur dolor deserunt perspiciatis consequuntur.",
                            Name = "Mozzarella Cheese"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Numquam rerum veniam qui saepe.",
                            Name = "Feta Cheese"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Dolores occaecati molestiae non et.",
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Aliquid libero fuga voluptas omnis.",
                            Name = "Green Peppers"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sint sint quas ipsum temporibus.",
                            Name = "Pepperoni"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Voluptatem omnis aut odio rerum.",
                            Name = "Parmesan Cheese"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Aut aliquid adipisci nemo consequuntur.",
                            Name = "Onions"
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2023, 4, 16, 14, 43, 50, 724, DateTimeKind.Utc).AddTicks(7349),
                            Status = 2,
                            TotalAmount = 610.639849449805960m
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2023, 11, 12, 21, 24, 22, 965, DateTimeKind.Utc).AddTicks(1041),
                            Status = 1,
                            TotalAmount = 1421.171550136604320m
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2023, 8, 3, 1, 58, 4, 230, DateTimeKind.Utc).AddTicks(4576),
                            Status = 1,
                            TotalAmount = 1215.827997418041000m
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2023, 10, 17, 5, 25, 24, 446, DateTimeKind.Utc).AddTicks(286),
                            Status = 1,
                            TotalAmount = 482.587243347702360m
                        },
                        new
                        {
                            Id = 5,
                            OrderDate = new DateTime(2023, 9, 6, 15, 25, 38, 562, DateTimeKind.Utc).AddTicks(3907),
                            Status = 1,
                            TotalAmount = 1421.953232475533920m
                        },
                        new
                        {
                            Id = 6,
                            OrderDate = new DateTime(2023, 1, 24, 21, 19, 32, 145, DateTimeKind.Utc).AddTicks(2772),
                            Status = 1,
                            TotalAmount = 1039.94646496136920m
                        },
                        new
                        {
                            Id = 7,
                            OrderDate = new DateTime(2023, 9, 17, 5, 40, 58, 911, DateTimeKind.Utc).AddTicks(6102),
                            Status = 0,
                            TotalAmount = 141.4160956635215520m
                        },
                        new
                        {
                            Id = 8,
                            OrderDate = new DateTime(2023, 2, 10, 21, 31, 45, 626, DateTimeKind.Utc).AddTicks(306),
                            Status = 1,
                            TotalAmount = 898.43411052526560m
                        },
                        new
                        {
                            Id = 9,
                            OrderDate = new DateTime(2023, 10, 22, 6, 0, 55, 936, DateTimeKind.Utc).AddTicks(5001),
                            Status = 0,
                            TotalAmount = 965.708769534578240m
                        },
                        new
                        {
                            Id = 10,
                            OrderDate = new DateTime(2023, 10, 25, 21, 4, 35, 711, DateTimeKind.Utc).AddTicks(1932),
                            Status = 1,
                            TotalAmount = 440.086971623862960m
                        },
                        new
                        {
                            Id = 11,
                            OrderDate = new DateTime(2023, 6, 22, 1, 27, 43, 128, DateTimeKind.Utc).AddTicks(2041),
                            Status = 1,
                            TotalAmount = 1133.63747469784560m
                        },
                        new
                        {
                            Id = 12,
                            OrderDate = new DateTime(2023, 3, 21, 20, 28, 55, 436, DateTimeKind.Utc).AddTicks(9835),
                            Status = 1,
                            TotalAmount = 1390.025915228774240m
                        },
                        new
                        {
                            Id = 13,
                            OrderDate = new DateTime(2023, 8, 11, 2, 40, 4, 541, DateTimeKind.Utc).AddTicks(9544),
                            Status = 1,
                            TotalAmount = 335.888394618354280m
                        },
                        new
                        {
                            Id = 14,
                            OrderDate = new DateTime(2023, 7, 2, 21, 30, 51, 584, DateTimeKind.Utc).AddTicks(8029),
                            Status = 2,
                            TotalAmount = 947.152145638667320m
                        },
                        new
                        {
                            Id = 15,
                            OrderDate = new DateTime(2023, 6, 21, 10, 36, 54, 535, DateTimeKind.Utc).AddTicks(6088),
                            Status = 2,
                            TotalAmount = 239.016087045435160m
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PortionId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PortionId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 14,
                            PortionId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 6,
                            PortionId = 15,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 8,
                            PortionId = 10,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 7,
                            PortionId = 14,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 7,
                            PortionId = 12,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 9,
                            PortionId = 2,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 2,
                            PortionId = 12,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 9,
                            PortionId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 4,
                            PortionId = 14,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 6,
                            PortionId = 14,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 8,
                            PortionId = 8,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 8,
                            PortionId = 4,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 6,
                            PortionId = 11,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 14,
                            OrderId = 13,
                            PortionId = 9,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 15,
                            OrderId = 14,
                            PortionId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 16,
                            OrderId = 3,
                            PortionId = 12,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 17,
                            OrderId = 5,
                            PortionId = 12,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 18,
                            OrderId = 7,
                            PortionId = 14,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 19,
                            OrderId = 13,
                            PortionId = 6,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 20,
                            OrderId = 5,
                            PortionId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 21,
                            OrderId = 8,
                            PortionId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 22,
                            OrderId = 9,
                            PortionId = 14,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 23,
                            OrderId = 1,
                            PortionId = 15,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 24,
                            OrderId = 8,
                            PortionId = 4,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 25,
                            OrderId = 7,
                            PortionId = 5,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 26,
                            OrderId = 7,
                            PortionId = 10,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 27,
                            OrderId = 3,
                            PortionId = 1,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 28,
                            OrderId = 9,
                            PortionId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 29,
                            OrderId = 14,
                            PortionId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 30,
                            OrderId = 10,
                            PortionId = 11,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 31,
                            OrderId = 1,
                            PortionId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 32,
                            OrderId = 9,
                            PortionId = 5,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 33,
                            OrderId = 6,
                            PortionId = 6,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 34,
                            OrderId = 3,
                            PortionId = 3,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 35,
                            OrderId = 3,
                            PortionId = 13,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 36,
                            OrderId = 8,
                            PortionId = 15,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 37,
                            OrderId = 1,
                            PortionId = 6,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 38,
                            OrderId = 9,
                            PortionId = 3,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 39,
                            OrderId = 15,
                            PortionId = 15,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 40,
                            OrderId = 10,
                            PortionId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 41,
                            OrderId = 11,
                            PortionId = 6,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 42,
                            OrderId = 10,
                            PortionId = 7,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 43,
                            OrderId = 13,
                            PortionId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 44,
                            OrderId = 13,
                            PortionId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 45,
                            OrderId = 1,
                            PortionId = 15,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 46,
                            OrderId = 4,
                            PortionId = 6,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 47,
                            OrderId = 9,
                            PortionId = 6,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 48,
                            OrderId = 1,
                            PortionId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 49,
                            OrderId = 3,
                            PortionId = 7,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 50,
                            OrderId = 7,
                            PortionId = 9,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 51,
                            OrderId = 6,
                            PortionId = 12,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 52,
                            OrderId = 12,
                            PortionId = 7,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 53,
                            OrderId = 10,
                            PortionId = 9,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 54,
                            OrderId = 6,
                            PortionId = 10,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 55,
                            OrderId = 10,
                            PortionId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 56,
                            OrderId = 7,
                            PortionId = 9,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 57,
                            OrderId = 3,
                            PortionId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 58,
                            OrderId = 13,
                            PortionId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 59,
                            OrderId = 12,
                            PortionId = 11,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 60,
                            OrderId = 13,
                            PortionId = 7,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Portion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("UnitId");

                    b.ToTable("Portions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 579.511296367045200m,
                            Description = "In eveniet voluptatem rerum laboriosam.",
                            DishId = 5,
                            Price = 616.584757536921600m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 385.80565777877600m,
                            Description = "Facilis enim esse accusamus rerum.",
                            DishId = 4,
                            Price = 751.32241349263200m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 437.41462446628800m,
                            Description = "Qui architecto vitae consequuntur dolor.",
                            DishId = 3,
                            Price = 300.352229597211200m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 557.937953415298000m,
                            Description = "Rerum numquam rerum veniam qui.",
                            DishId = 4,
                            Price = 597.876540011668800m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 340.218343464759200m,
                            Description = "Occaecati molestiae non et numquam.",
                            DishId = 4,
                            Price = 701.163321966847200m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 401.778772381031200m,
                            Description = "Voluptas omnis ratione sint sint.",
                            DishId = 1,
                            Price = 831.138423379109600m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 554.79099021982000m,
                            Description = "Cumque voluptatem omnis aut odio.",
                            DishId = 2,
                            Price = 844.435534553804800m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 409.659736701128800m,
                            Description = "Aliquid adipisci nemo consequuntur et.",
                            DishId = 1,
                            Price = 799.290544446227200m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 402.142979671314000m,
                            Description = "Natus et aliquid voluptatem recusandae.",
                            DishId = 3,
                            Price = 387.933481199636000m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 450.50262727332400m,
                            Description = "Voluptate blanditiis veniam tempora dignissimos.",
                            DishId = 4,
                            Price = 307.63638471608800m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 547.748195728169600m,
                            Description = "Ipsa explicabo qui architecto sed.",
                            DishId = 1,
                            Price = 704.935183238673600m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 417.07221074824800m,
                            Description = "Est est necessitatibus sit ipsa.",
                            DishId = 3,
                            Price = 454.221372797256800m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 259.485794445260400m,
                            Description = "Nihil in ea mollitia sequi.",
                            DishId = 5,
                            Price = 356.403831092828800m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = 219.901462094812400m,
                            Description = "Voluptas ut voluptatum voluptatibus id.",
                            DishId = 2,
                            Price = 780.446354570075200m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 15,
                            Amount = 220.6978339798272800m,
                            Description = "Qui quia vitae ut earum.",
                            DishId = 4,
                            Price = 752.584564570609600m,
                            UnitId = 1
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "g"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ml"
                        },
                        new
                        {
                            Id = 3,
                            Name = "pcs"
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.DishIngredient", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Dish", null)
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.DAL.Entities.Ingredient", null)
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.DAL.Entities.Portion", "Portion")
                        .WithMany("OrderItems")
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Portion");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Portion", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Dish", "Dish")
                        .WithMany("Portions")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.DAL.Entities.Unit", "Unit")
                        .WithMany("Portions")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Dish", b =>
                {
                    b.Navigation("DishIngredients");

                    b.Navigation("Portions");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Ingredient", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Portion", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Unit", b =>
                {
                    b.Navigation("Portions");
                });
#pragma warning restore 612, 618
        }
    }
}
